### ISSUE TITLE
URL設計

### ISSUE THREAD

**Issue by psbss** [jdkfx/piqraise-web#8]
クライアント側で利用するURLを設計する。

**Comment by psbss** [comment]
| URL | 機能 |
| --| -- |
| gtp.com | トップページ |
| gtp.com/[userID] | ユーザトップページ(本日のToDoリスト) |
| gtp.com/[userID]?date=YYYYMMDD | YYYY/MM/DD時点のToDoリスト |
| gtp.com/settings | ユーザ設定ページ |
| gtp.com/login | ユーザログインページ |

**Comment by jdkfx** [comment]
### 認証のURLについて

#### 現在のURL
URL | 機能
-- | --
gtp.com/login | ユーザログインページ

#### 変更したいURL
URL | 機能
-- | --
gtp.com/login | ユーザログインページ
gtp.com/login/auth/twitter | ユーザログインURL
gtp.com/logout/auth/twitter | ユーザログアウトURL

``ユーザログインページ`` は `` ユーザログインURL `` と `` ユーザログアウトURL ``を含む

将来的に他のドライバを使用する可能性が見えてきたため、どのドライバを使って認証を行うのかURL内に含めたい
イメージ的には画像のとおり
![image](https://user-images.githubusercontent.com/40142697/107847200-d240a380-6e2c-11eb-94ba-62046ed6e793.png)

**Comment by jdkfx** [comment]
ToDo：ログイン後に `` gtp.test/todos `` にリダイレクトしないようにする

**Comment by psbss** [comment]
| URL | 機能 |
| --| -- |
| gtp.com | トップページ |
| gtp.com/[userID] | ユーザトップページ(本日のToDoリスト) |
| gtp.com/[userID]/YYYYMMDD | YYYY/MM/DD時点のToDoリスト |
| gtp.com/settings | ユーザ設定ページ |
| gtp.com/login | ユーザログインページ |
| gtp.com/login/auth/twitter| ユーザTwitterログイン |
| gtp.com/logout | ユーザログアウト(gtp.com/logout/auth/twitter) |
| gtp.com/[hash] | 公開したTodoのページ |

**Comment by jdkfx** [comment]
URL | 機能
-- | --
gtp.com | トップページ
gtp.com/[userID] | ユーザトップページ(本日のToDoリスト)
gtp.com/[userID]/YYYYMMDD | YYYY/MM/DD時点のToDoリスト
gtp.com/settings | ユーザ設定ページ
gtp.com/login | ユーザログインページ
gtp.com/login/auth/twitter | ユーザTwitterログイン
gtp.com/logout | ユーザログアウト(gtp.com/logout/auth/twitter)
**gtp.com/[userID]/YYYYMMDD/[hash]** | **公開したTodoのページ**

こちらのほうがいいのではないかと思う

**Comment by psbss** [comment]
認証系をどうするか迷ってて、
デフォルトでTodoリストは非公開にしておいて、公開にすると外部からでも```gtp.com/[userID]/YYYYMMDD```にアクセスできるようにするとかlaravel側で操作できる？

**Comment by jdkfx** [comment]
不可能ではないと思う。
やったことはないのでできるかは分からないがやってみる価値はあり。

**Comment by psbss** [comment]
とりあえずやってみる方向でお願いします！

**Comment by jdkfx** [comment]
- 上記 `gtp.com` を `piqraise.com` に変更した形で動かせるようにします

**Comment by satorunooshie** [comment]
URL | 機能
-- | --
gtp.com | トップページ
gtp.com/[userID] | ユーザトップページ(本日のToDoリスト)
gtp.com/[userID]/YYYYMMDD | YYYY/MM/DD時点のToDoリスト
gtp.com/settings | ユーザ設定ページ
gtp.com/login | ユーザログインページ
gtp.com/login/auth/twitter | ユーザTwitterログイン
gtp.com/logout | ユーザログアウト(gtp.com/logout/auth/twitter)
**gtp.com/[userID]/YYYYMMDD/[hash]** | **公開したTodoのページ**

これuserIDいらなくね？
ユーザートップページとか、userID渡さなくてもログインユーザー取得できるからいらなくねって思ってしまった
公開用はuserID必要だけど
URL | 機能
-- | --
gtp.com | トップページ
gtp.com/today | ユーザトップページ(本日のToDoリスト)
gtp.com/YYYYMMDD | YYYY/MM/DD時点のToDoリスト
gtp.com/settings | ユーザ設定ページ
gtp.com/login | ユーザログインページ
gtp.com/login/auth/twitter | ユーザTwitterログイン
gtp.com/logout | ユーザログアウト(gtp.com/logout/auth/twitter)
**gtp.com/[userID]/YYYYMMDD/[hash]** | **公開したTodoのページ**
